plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
    destinationDirectory.set(file("../app_pojavlauncher/src/main/assets/components/runelite_audio/"))
    archiveBaseName.set("runelite_audio")
    manifest {
        attributes("Manifest-Version": "1.0")
    }
    preserveFileTimestamps = false
    reproducibleFileOrder = true
    def versionFile = new File(project(":app_pojavlauncher").projectDir,
            "src/main/assets/components/runelite_audio/version")
    def jarFile = archiveFile.get().asFile
    doLast {
        writeVersionFile(jarFile, versionFile)
    }
    outputs.file(versionFile)
}
